### ISSUE TITLE
Here are another two usefull tools in single-cell analyses

### ISSUE THREAD

**Issue by screamer** [seandavi/awesome-single-cell#151]
https://github.com/ChenMengjie/VIPER
https://github.com/ChenMengjie/Citrus

**Comment by seandavi** [comment]
Are you OK with doing a pull request? That helps keep track of who did what and also ensures that explanations are correct. If not, just let me know and I can add when I get a moment.

**Comment by screamer** [comment]
Sorry, I just understood how it works. I will do a pull request. Thank you!
