### ISSUE TITLE
about allelic normalization or imputation

### ISSUE THREAD

**Issue by Hemantcnaik** [seandavi/awesome-single-cell#206]
Hello I am doing single cell allelic analysis, main objective is to do transcriptional burst analysis, i have Choose SCALE which is using spike in for data normalization but the problem is I don't have the spike in information SCALE mentioned without normalization its not good to do SCALE. can you please suggest me any tools are method  I can use your help will be appreciated

**Comment by seandavi** [comment]
I don't have a direct answer for you. I'd suggest asking this question on https://biostars.org. You may get an answer here, but the community of folks ready to answer questions is much larger there.
