### ISSUE TITLE
adding separate section for ATAC-seq / combining methods?

### ISSUE THREAD

**Issue by drkeoni** [seandavi/awesome-single-cell#75]
Thanks for putting together and maintaining this list, it's a great community resource!

I noticed that SCRAT is listed in the RNA-seq section when it's really ATAC-seq...or epigenomics in general.  Would you consider changing the name of the "Methylation" section to Epigenomics and then add SCRAT (and some other new scATAC-seq tools) to this?  Single-cell epigenomics seems to be an emerging field and there's probably a lot of tools that could go in this category.

On a related note, there also seems to be an emerging theme of tools that are particularily designed to merge disparate single-cell data types (for example "Matcher", listed in the Other section, for processing scRNA-seq and sc-"Epigenomics" (methylation or ATAC-seq).  This seems like another section that could be brought out?  Something like "Combining multiple data types"   

Thanks for considering my suggestions.

Jon Sorenson

**Comment by seandavi** [comment]
I'm really open to "adapting" the list to address changing themes and to re-organize. Your ideas sound great. Would you mind making the adjustments you feel appropriate and submitting pull requests?

**Comment by seandavi** [comment]
And how about "Multi-assay data integration" for the "combining data types"?

**Comment by drkeoni** [comment]
Sounds good, I'll put together a pull request.  I'll go with "Multi-assay data integration" for the new section.

**Comment by seandavi** [comment]
closed with #76, thanks.
