### ISSUE TITLE
Adding list of people (e.g., for talk invitations)

### ISSUE THREAD

**Issue by PeteHaitch** [seandavi/awesome-single-cell#9]
Great list, Sean and co. Would you be open to adding to this resource a list of people working on stats/computational methods in single-cell genomics/biology? 

My reasons are somewhat selfish - I'm trying to organise a conference session and want a balanced female and male representation in my invitations. So I started compiling a list of women I'd love to see give a talk. I was thinking of sticking it somewhere online and hopefully getting community contributions and updates.

**Comment by seandavi** [comment]
Totally.  Just add a new section.  I'll leave it to you to define the "format" that makes the most sense for that section?
