### ISSUE TITLE
Error in file(file, "rt") : cannot open the connection

### ISSUE THREAD

**Issue by shawnql08** [seandavi/awesome-single-cell#98]
Using Seurat for single cell analysis, there is problem:

> pbmc <- FindClusters(object = pbmc, reduction.type = "pca", dims.use = 1:10, 
+                      resolution = 0.6, print.output = 0, save.SNN = TRUE)
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: running command 'java -jar "C:/Program Files/R/R-3.4.4/library/Seurat/java/ModularityOptimizer.jar" "C:\Users\huang\AppData\Local\Temp\RtmpuEbE34\file331c11c26286_edge_45021.txt" "C:\Users\huang\AppData\Local\Temp\RtmpuEbE34\file331c11c26286_output_45021.txt" 1 0.6 1 100 10 0 0' had status 127 
2: In file(file, "rt") : cannot open file 'C:\Users\huang\AppData\Local\Temp\RtmpuEbE34\file331c11c26286_output_45021.txt': No such file or directory

How can I solve this problem? 

Thank you!

**Comment by emilypai1125** [comment]
This is the java issue.

Are you running it on Mac system? If so, look at the error message. It tells you which java development tool you should download to fix this problem. ( I ran into this problem months ago and got it fixed with the java tool ).

**Comment by seandavi** [comment]
I'd suggest getting in touch with the Seurat authors: http://satijalab.org/seurat/contact.html.
